version: 2.1

orbs:
  win: circleci/windows@2.2.0

workflows:
  version: 2
  build:
    jobs:
      #- build-win
      - build-mac
      - build-linux


jobs:
  build-win:
    executor:
      name: win/default
      size: medium

    parameters:
      msyspath:
        type: string
        default: "/c/tools/msys64/usr/bin:/c/tools/msys64/mingw64/bin:/c/tools/msys64/mingw64/lib/go/bin"

    steps:
      - checkout
      - run:
          name: Install MSYS2
          shell: powershell.exe
          command: |
            choco install -y msys2
      - run:
          name: Install prerequisites
          shell: C:\\tools\\msys64\\usr\\bin\\bash
          environment:
            PATH: "/c/tools/msys64/usr/bin:/c/tools/msys64/mingw64/bin:/c/tools/msys64/mingw64/lib/go/bin"
          command: |
            /c/tools/msys64/usr/bin/pacman -Sy --noconfirm \\
            mingw-w64-x86_64-toolchain \\
            mingw-w64-x86_64-libusb \\
            mingw-w64-x86_64-go \\
            mingw-w64-x86_64-pkg-config \\
            git
      - run:
          name: Build
          shell: C:\\tools\\msys64\\usr\\bin\\bash
          environment:
            PATH: "/c/tools/msys64/usr/bin:/c/tools/msys64/mingw64/bin:/c/tools/msys64/mingw64/lib/go/bin"
          command: |
            go build .

  build-mac:
    macos:
      xcode: 10.1.0
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Update Homebrew
          command: brew update
      - run:
          name: Install prerequisites
          command: brew install libusb golang
      - run:
          name: Build
          environment:
            CGO_CFLAGS: -Wno-deprecated-declarations
          command: go build .

  build-linux:
    docker:
      - image: circleci/golang:buster
    resource_class: small
    steps:
      - checkout
      - run:
          name: Install prerequisites
          command: sudo apt install libusb-1.0.0-dev
      - run:
          name: Build
          environment:
            CGO_CFLAGS: -Wno-deprecated-declarations
          command: go build .
